### RNN_handwritten_recognition

In [3]:
import torch
import torchvision

In [4]:
train_data = torchvision.datasets.MNIST(
    root='./mnist/',
    train = True,
    transform = torchvision.transforms.ToTensor(),
    download = True
)

Processing...
Done!


### create train data set

In [5]:
train_data_set = torch.utils.data.DataLoader(dataset=train_data, batch_size=50,shuffle=True)


### download test data

In [6]:
test_data = torchvision.datasets.MNIST(
    root='./mnist/',
    train = False
)

### create test data set

In [7]:
test_x = torch.unsqueeze(test_data.test_data, dim=1).type(torch.FloatTensor)[:2000]/255
test_y = test_data.test_labels[:2000]

### create RNN model

In [33]:
class LpRnnModel(torch.nn.Module):
    def __init__(self):
        super(LpRnnModel, self).__init__()
        self.rnn = torch.nn.LSTM(
            input_size = 28,
            hidden_size = 64,
            num_layers = 1,
            batch_first = True
        )
        self.out = torch.nn.Linear(64,10)
        
    def forward(self, input):
        r_out, (h_n, h_c) = self.rnn(input, None)
        out = self.out(r_out[:,-1,:])
        return out
        


### instantiation RNN model

In [34]:
model = LpRnnModel()

### show model

In [35]:
print(model)

LpRnnModel(
  (rnn): LSTM(28, 64, batch_first=True)
  (out): Linear(in_features=64, out_features=10, bias=True)
)


### create optimizer

In [36]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

### create loss function

In [37]:
loss_function = torch.nn.CrossEntropyLoss()

### train data

In [40]:
for epoch in range(4):
    for step, (images, labels) in enumerate(train_data_set):
        images = images.view(-1, 28, 28)
        output = model(images)
        loss = loss_function(output, labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if step % 100 == 0:
            print('step:', step)

step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100
step: 0
step: 100
step: 200
step: 300
step: 400
step: 500
step: 600
step: 700
step: 800
step: 900
step: 1000
step: 1100


### test model

In [47]:
output = model(test_x.view(-1,28,28))
print(output)
pred = torch.max(output, 1)[1].data.numpy()
print(pred)
print(test_y)
sumValue = 0
for index in range(2000):
    if pred[index] == test_y[index]:
        sumValue += 1.0
    else:
        print(index, pred[index], test_y[index])
accuracy = float(sumValue / float(len(test_y)))
print(accuracy)

tensor([[-5.8902,  0.3118, -0.0079,  ...,  9.9473, -3.7547,  0.7059],
        [-2.2920,  0.6756, 10.1040,  ..., -0.6901, -1.3821, -4.1922],
        [-5.8612, 12.1498, -3.0362,  ..., -0.3553,  0.7722, -2.7464],
        ...,
        [-5.3020, -0.9501, -2.8806,  ..., -3.6264,  1.0152, -0.7813],
        [-1.6402, -4.8339, -1.4461,  ..., -2.3657, -1.1507,  7.8918],
        [-5.9501, -3.7440, -2.3580,  ..., -2.8311, -0.3545,  1.9548]],
       grad_fn=<ThAddmmBackward>)
[7 2 1 ... 3 9 5]
tensor([7, 2, 1,  ..., 3, 9, 5])
8 6 tensor(5)
18 8 tensor(3)
62 5 tensor(9)
247 2 tensor(4)
259 0 tensor(6)
321 7 tensor(2)
324 1 tensor(0)
340 3 tensor(5)
412 3 tensor(5)
435 9 tensor(8)
445 0 tensor(6)
464 7 tensor(3)
495 2 tensor(8)
613 8 tensor(2)
619 3 tensor(1)
659 1 tensor(2)
684 2 tensor(7)
691 7 tensor(8)
844 3 tensor(8)
916 2 tensor(4)
947 9 tensor(8)
951 9 tensor(5)
965 5 tensor(6)
1014 5 tensor(6)
1033 3 tensor(8)
1039 2 tensor(7)
1101 2 tensor(8)
1226 2 tensor(7)
1232 4 tensor(9)
1260 1 tensor(7